using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class SearchVehicleRenalContract
    {
        public string? DocTrNo { get; set; }
        public int? TrNo { get; set; }
        public DateTime? TrDate { get; set; }
        public string? ManualTrNo { get; set; }
        public DateTime? ExpectedStartDate { get; set; }
        public DateTime? RealStartDate { get; set; }
        public DateTime? GetOutDate { get; set; }
        public byte? PaymentMethod { get; set; }
        public string? HotelRoom { get; set; }
        public long? StartCounter { get; set; }
        public long? EndCounter { get; set; }
        public long? ConsumedCounter { get; set; }
        public long? AllowanceCounter { get; set; }
        public long? ExtraCounter { get; set; }
        public long? DailyCounter { get; set; }
        public decimal? FuelIn { get; set; }
        public decimal? FuelOut { get; set; }
        public string? VisaNo { get; set; }
        public string? Type { get; set; }
        public DateTime? VisaExpiryDate { get; set; }
        public string? VisaCode { get; set; }
        public decimal? VisaAmount { get; set; }
        public bool? VisaApproved { get; set; }
        public decimal? InsuranceValue { get; set; }
        public int? ContractDays { get; set; }
        public decimal? DayPrice { get; set; }
        public decimal? InvTotal { get; set; }
        public decimal? DeliveryCost { get; set; }
        public decimal? DriverCost { get; set; }
        public decimal? FuelCost { get; set; }
        public decimal? MaintenanceCost { get; set; }
        public decimal? DiscPercent { get; set; }
        public decimal? DiscAmount { get; set; }
        public decimal? DiscPercent2 { get; set; }
        public decimal? DiscAmount2 { get; set; }
        public decimal? DiscPercent3 { get; set; }
        public decimal? DiscAmount3 { get; set; }
        public decimal? DiscPercent4 { get; set; }
        public decimal? DiscAmount4 { get; set; }
        public decimal? PriceAfterTax { get; set; }
        public decimal? ExpenValue { get; set; }
        public decimal? PaidPrice { get; set; }
        public decimal? NetPrice { get; set; }
        public decimal? Commision { get; set; }
        public decimal? Rate { get; set; }
        public decimal? NetPriceBeforCurr { get; set; }
        public decimal? ExpenValueBeforCurr { get; set; }
        public decimal? ExpenValueWithCurr { get; set; }
        public decimal? NotPaid { get; set; }
        public bool? IsPaid { get; set; }
        public decimal? TotalPurchInv { get; set; }
        public decimal? TotalPayment { get; set; }
        public decimal? TotalPaidReciept { get; set; }
        public decimal? TotalSalesInv { get; set; }
        public decimal? TotalCost { get; set; }
        public decimal? TotalCostBeforeCurr { get; set; }
        public decimal? Profit { get; set; }
        public bool? IsClosed { get; set; }
        public DateTime? ClosingDate { get; set; }
        public string? Tel { get; set; }
        public string? Fax { get; set; }
        public string? Email { get; set; }
        public string? Email2 { get; set; }
        public string? Email3 { get; set; }
        public string? Email4 { get; set; }
        public string? Address { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? Tel2 { get; set; }
        public string? Tel3 { get; set; }
        public string? Tel4 { get; set; }
        public string? Tel5 { get; set; }
        public string? AddField1 { get; set; }
        public string? AddField2 { get; set; }
        public string? AddField3 { get; set; }
        public string? AddField4 { get; set; }
        public string? AddField5 { get; set; }
        public string? CustomerCode { get; set; }
        public string? CustomerDescA { get; set; }
        public string? VehicleCode { get; set; }
        public string? VehicleName1 { get; set; }
        public string? VehicleName2 { get; set; }
        public string? RegNo { get; set; }
        public string? BodyNo { get; set; }
        public string? MotorNo { get; set; }
        public long? StartCounterNo { get; set; }
        public long? CounterNo { get; set; }
        public int? YearModel { get; set; }
        public string? Color { get; set; }
        public string? OwnerName { get; set; }
        public string? OwnerAddress { get; set; }
        public string? HotelCode { get; set; }
        public string? HotelName1 { get; set; }
        public string? HotelName2 { get; set; }
        public string? FirstDriverCode { get; set; }
        public string? DriverName1 { get; set; }
        public string? DriverName2 { get; set; }
        public string? SecondDriverCode { get; set; }
        public string? SecondDriverName1 { get; set; }
        public string? SecondDriverName2 { get; set; }
        public string? ThirdDriverCode { get; set; }
        public string? ThirdDriverName1 { get; set; }
        public string? ThirdDriverName2 { get; set; }
        public string? Nationality { get; set; }
        public DateTime? CustomerDateOfBirth { get; set; }
        public DateTime? CustomerCarLicenseExpiryDate { get; set; }
        public DateTime? CustomerCarLicenseIssueDate { get; set; }
        public string? CustomerCarLicenseNo { get; set; }
        public string? CustomerCarLicenseIssuePlace { get; set; }
        public bool? CustomerInternationalLicense { get; set; }
        public DateTime? CustomerPassPortIssueDate { get; set; }
        public string? CustomerPassPortIssuePlace { get; set; }
        public string? CustomerPassPortNo { get; set; }
        public string? CustId { get; set; }
        public string? FirstDriverDriverLicense { get; set; }
        public string? FirstDriverLicenseDescription { get; set; }
        public DateTime? FirstDriverLicenseIssueDate { get; set; }
        public string? FirstDriverLicenseLegalPlaceas { get; set; }
        public DateTime? FirstDriverLicenseRenewalDate { get; set; }
        public string? FirstDriverId { get; set; }
        public string? PassPort { get; set; }
        public DateTime? FirstDriverDateOfBirth { get; set; }
        public decimal? Vat { get; set; }
        public int? BookId { get; set; }
        public string? TermCode { get; set; }
        public string? TermName { get; set; }
        public byte? TermType { get; set; }
        public int? TermId { get; set; }
        public int? StoreId { get; set; }
    }
}
